[build]
  functions = "netlify/functions"  # Ubicaci贸n de las funciones
  publish = "build"                # Ubicaci贸n de los archivos del frontend (por ejemplo, la carpeta build de React)

[[redirects]]
  from = "/entrenamientos/*"
  to = "/.netlify/functions/entrenamientos.js/:splat"  # Redirige las solicitudes a la funci贸n backend de Netlify
  status = 200

[[redirects]]
  from = "/ejercicios/*"
  to = "/.netlify/functions/ejercicios.js/:splat"  # Redirige las solicitudes a la funci贸n backend de Netlify
  status = 200
